### PR TITLE
[Sprint: 46] XD-2858,2884: Module dynamic ClassPath

### PR DESCRIPTION
**Pull request by ericbottard**
This PR does the following:
* Clean up ModuleUtils, introducing various utility methods, so that there is less code duplication. Also, remove passing around a module classloader when it was not needed
* introduce the notion of 3 time based classloaders for a module:
  1. a very simple classloader, used to load "resources", ie stuff that is inside the first level of a module archive (such as the module properties file, or an xml config file). That classloader does not "see" other jars (such as those in `lib/`), neither does it see a parent classloader  - no more "found multiple properties files" coming from `xd.home/config/*.properties` when actually none were in the module[*]
  2. a "discovery time" classloader that is used before a module is actually deployed. This classloader sees jars in lib/*.jar and is used eg to display options, etc. It needs to see `OptionsMetadata` classes
  3. a real "runtime classloader" that is used when a module is deployed. Here comes the crux of this PR: This classloader is driven by the `module.classpath` key of the module properties file, which can list libraries locations. Details below:

`module.classloader` can be a comma separated list of library paths, which are handled like this:
* if they start with a slash, paths are understood as "inside" the module archive
* if not (especially if starting with a protocol, such as `file:`) they're handled like well known spring Resources
* the default value is `/lib/*.jar,/lib/*.zip` which amounts to the "discovery time" classloader
* those paths may contain `${foo}` placeholders, and those placeholders are resolved against the actual module options property source. This means in particular that
  * stuff like `${xd.home}` can be used
  * so can module options. The aim being ...

... to allow for this (subject of another PR):

HDFS module:
`module.classpath = /lib/*.jar,${xd.home}/lib/hadoop/${distro}/*.jar`

`http | hdfs --distro=phd1`

[*] $xd.home has also been removed from the system classpath in this PR 

I'm assigning @dturanski for review as he's certainly the most knowledgeable about ModuleUtils and a module CL. Details of the dynamic feature have been discussed with Thomas and MarkP though

### CODE REVIEW

**Comment by dturanski** [comment]
LGTM; merging;

**Comment by dturanski** [comment]
Whoops: Getting test failures after rebase:
```
org.springframework.xd.module.core.ModuleFactoryTests > createJavaConfiguredModule FAILED
    java.lang.RuntimeException at ModuleFactoryTests.java:50
        Caused by: java.io.FileNotFoundException at ModuleFactoryTests.java:50

org.springframework.xd.module.core.ModuleFactoryTests > invalidJavaConfiguredModuleShouldThrowException FAILED
    java.lang.RuntimeException at ModuleFactoryTests.java:70
        Caused by: java.io.FileNotFoundException at ModuleFactoryTests.java:70

org.springframework.xd.module.info.DefaultSimpleModuleInformationResolverTests > returnFound FAILED
    java.lang.AssertionError at DefaultSimpleModuleInformationResolverTests.java:57

org.springframework.xd.module.support.ModuleUtilsTests > testModuleOptionInterpolation FAILED
    java.lang.NullPointerException at ModuleUtilsTests.java:45
```

**Comment by ericbottard** [comment]
I rebased on top of 58e5c67d111d6b178e06aa3c6082370403371676 (arrived at 4370650d62a052b28ba96bd44bd2a074729adf8d) and successfully ran `./gradlew clean copyInstall`

**Comment by ericbottard** [comment]
Not pushing the rebased code, in case we need to investigate

**Comment by dturanski** [comment]
Strange. I will debug from here.

**Comment by ericbottard** [comment]
Maybe another case of not commiting empty dirs?

**Comment by dturanski** [comment]
Debugging ModuleFactoryTests>createJavaConfiguredModule ... 

in ModuleUtils L 134:

resource = {org.springframework.core.io.ClassPathResource@1201}"class path resource [config/spring-module.properties]"
path = {java.lang.String@1224}"config/spring-module.properties"
value = {char[31]@1261}
hash = -664555422
classLoader = {org.springframework.xd.module.support.ParentLastURLClassLoader@1225}"ParentLastURLCL\r\nURLs: [file:/Users/dturanski/s2build/spring-xd/spring-xd-module/build/classes/test/ModuleFactoryTests/modules/processor/siDslModule.jar]\nParent CL: org.springframework.xd.module.support.NullClassLoader@17046283\nSystem CL: sun.misc.La...
system = {sun.misc.Launcher$ExtClassLoader@1229}
byPassSystemClassLoaderForResources = true
ucp = {sun.misc.URLClassPath@1230}
acc = {java.security.AccessControlContext@1231}
closeables = {java.util.WeakHashMap@1232} size = 0
initialized = true
pdcache = {java.util.HashMap@1233} size = 0
parent = {org.springframework.xd.module.support.NullClassLoader@1234}
parallelLockMap = null
package2certs = {java.util.Hashtable@1235} size = 0
classes = {java.util.Vector@1236} size = 0
defaultDomain = {java.security.ProtectionDomain@1237}"ProtectionDomain  (null <no signer certificates>)\n ParentLastURLCL\r\nURLs: [file:/Users/dturanski/s2build/spring-xd/spring-xd-module/build/classes/test/ModuleFactoryTests/modules/processor/siDslModule.jar]\nParent CL: org.springframework.xd.module.supp...
domains = {java.util.HashSet@1238} size = 0
packages = {java.util.HashMap@1239} size = 0
nativeLibraries = {java.util.Vector@1240} size = 0
assertionLock = {org.springframework.xd.module.support.ParentLastURLClassLoader@1225}"ParentLastURLCL\r\nURLs: [file:/Users/dturanski/s2build/spring-xd/spring-xd-module/build/classes/test/ModuleFactoryTests/modules/processor/siDslModule.jar]\nParent CL: org.springframework.xd.module.support.NullClassLoader@17046283\nSystem CL: sun.misc.La...
defaultAssertionStatus = false
packageAssertionStatus = null
classAssertionStatus = null
clazz = null

Resource.getInputStream() throws FNFE "config/spring-module.properties".  Hard to believe it works fine for you.

**Comment by ericbottard** [comment]
OK, I was able to reproduce, but in IDEA only. After much hair pulling, I finally understood what the problem was (still don't get why it built fine from the CLI).
When we return Resources, we need to make sure that the CL backing them is still open (I attempted to be clean with this PR, but I guess we'll need to revisit and maybe change the type of what we return to have more control over the lifecycle of things).

So, this last commit (I also pushed the rebase) "solves" the issues (note that the last doesn't pass on master either)

**Comment by dturanski** [comment]
Down to these two now:

```
org.springframework.xd.module.info.DefaultSimpleModuleInformationResolverTests > returnFound FAILED
    java.lang.AssertionError at DefaultSimpleModuleInformationResolverTests.java:57
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
objc[26050]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

org.springframework.xd.module.support.ModuleUtilsTests > testModuleOptionInterpolation FAILED
    java.lang.NullPointerException at ModuleUtilsTests.java:45
```

**Comment by ericbottard** [comment]
Are you saying you get all those errors when building with `./gradlew clean copyInstall` ?
I see (saw) none of those.

**Comment by dturanski** [comment]
./gradlew clean build

**Comment by ericbottard** [comment]
OMG, just tested. This is very wrong.
I always assumed `copyInstall` at least covered `build`. Will investigate.

**Comment by ericbottard** [comment]
Fixed the last test failure I saw (with ./gradlew build). I'm not seeing anything wrong with `ModuleUtilsTests ` (neither in IDEA)

**Comment by dturanski** [comment]
copyInstall works for me too. After the latest commit, I'm down to 1 fail with clean build:

org.springframework.xd.module.support.ModuleUtilsTests > testModuleOptionInterpolation FAILED
    java.lang.NullPointerException at ModuleUtilsTests.java:45

**Comment by ericbottard** [comment]
OK, I fixed the last problem. This one indeed one a case of too aggressive `.gitignore`. Pheww

**Comment by ericbottard** [comment]
Also added doco

**Comment by dturanski** [comment]
Merged;

**Pull request closed without merging**
