### PR TITLE
[Sprint: 51 (GA)] XD-3177: Make Rabbit Bus Properties Optional

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/XD-3177

Fall back to boot defaults for rabbitmq properties if no
application.yml or servers.yml on classpath.

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
I thnk this change will break rabbitmq modules that use `RabbitConnectionMixin` module option metadata. We need to update the defaults in the Mixin as well.

**Comment by garyrussell** [comment]
Hmmmm - this simply makes passing the properties into the bus optional when using it outside of a Spring XD container (in spring-bus).

You are probably right if the mixin is used in a spring-bus module but it's not relevant for existing uses of the mixin within XD.

**Comment by ilayaperumalg** [comment]
Yeah, I was just thinking about the protection for the module options when there are no application.yml/servers.yml config in CP. Inside XD we would always have application.yml protecting this.

**Comment by ilayaperumalg** [comment]
It looks like defining empty default values for the placeholders at the `RabbitConnectionMixin` would violate the module option validation constraints.

**Comment by ilayaperumalg** [comment]
LGTM, merging the changes as the above mentioned module options wouldn't have any impact within the context of XD.

**Comment by ilayaperumalg** [comment]
Rebased and merged as 6de993eb21c99d9abc0184b511dc6a011b89b026

**Pull request closed without merging**
