### PR TITLE
[XD-2769] Making receive() and receivePayload() consistent with Spring Integration

### PR DESCRIPTION
**Pull request by kdowbecki**
Should tests for changed classes be provided with this pull request? I searched the project but I haven't found existing tests for NamedChannelSink, please point me in the right direction.

### CODE REVIEW

**Comment by garyrussell** [comment]
We can't use blocking `receive()` in tests (see my comment on the JIRA); use a long enough timeout instead.

**Comment by dturanski** [comment]
I would even be ok removing receive() and receivePayload() from NamedChannelSink. The tests for these classes are in ExampleProcessingChainTests.

**Comment by dturanski** [comment]
@garyrussell, @kdowbecki  I think it's best if we remove receive() and receivePayload() altogether since  blocking methods should never be used for tests and backing with a long timeout is 1) inconsistent and 2) difficult to choose an appropriate value.

**Comment by kdowbecki** [comment]
I like those blocking methods because I prefer to enforce hard timeouts globally. From where I stand using a blocking ```receive()``` or ```receive(int)``` with huge timeout is equally bad.

Ideally there should be a way to distinguish between timeout and no message produced by the component (e.g. Spring Integration <service-activator requires-reply=false/> or <filter/> inside the module). Currently it's always timeout and null is returned from receive(int ).

If you think that removing them will improve the test framework usability and guard developers from doing a build-halting mistake please go ahead. As it is written now ```receive()``` can't be used so no one should complain.

**Comment by dturanski** [comment]
closed https://github.com/spring-projects/spring-xd/commit/a5a6a556420a7a07024a08bcc2df526d608c8171

**Pull request closed without merging**
