### PR TITLE
[Sprint: 49] XD-3036: Fix various asciidoc issues

### PR DESCRIPTION
**Pull request by ericbottard**
Also removed conditional github titles.

### CODE REVIEW

**Comment by ghillert** [comment]
@ericbottard  Just to be super-sure - What was the reason to remove `GuideHttp2Gemfire.asciidoc`?

Otherwise this looks good and is ready for merging.

**Comment by ericbottard** [comment]
It's not included from anywhere. I'm not even sure it was meant to be in
the guide subfolder.

**Comment by ghillert** [comment]
LGTM then. Merging.

**Comment by ghillert** [comment]
Merged. 133ba9a203140a51022edf4a590e0f75733eefb5

**Pull request closed without merging**
