### PR TITLE
Jms transport - JIRA XD-1928

### PR DESCRIPTION
**Pull request by sathiyas**
To add JMS as transport, the following artifacts are modified/created in the branch jms-transport.

Modifed
   build.gradle
   settings.gradle

Created
  spring-xd-messagebus-jms/src/main/java/org/springframework/xd/dirt/integration/jms/JMSMessageBus.java
  spring-xd-messagebus-jms/src/main/java/org/springframework/xd/dirt/integration/jms/package-info.java
  spring-xd-messagebus-jms/src/main/resources/META-INF/spring-xd/bus/jms-bus.xml

### CODE REVIEW

**Comment by sathiyas** [comment]
Hello, looks like the build failed on pullDocs, as described in https://stackoverflow.com/questions/27905817/spring-xd-dist-task-fails-when-building-from-a-branch 

Should I resubmit the changes in master rather than a branch I chose or you al can configure it to rerun with -PwikiBranch=origin/master argument? 

Thanks
Sathiya

**Comment by dturanski** [comment]
Thanks for the PR. In general, XD needs a way to plug in JMS providers (other than activemq). This makes the configuration fairly complex but is an important requirement. In general, think about how we would connect to an existing JMS environment with the broker on a remote host, along with the possibility to support for provider specific settings.  Take a look at https://github.com/spring-projects/spring-xd/tree/master/modules/source/jms/config[jms source] to get some ideas, although an MB implementation likely will be handled differently. Also, the MessageBus itself should be more robust, e.g., the unsupported operations should be implemented.

**Comment by sathiyas** [comment]
Thanks Dave, I am looking into the enhancement, I will submit again ready for pull.

**Comment by dturanski** [comment]
@sathiyas - Do plan to update this PR any time soon?  If so, let me know if you have any questions.  Otherwise we will close it.

**Comment by sathiyas** [comment]
Please close it for now, I will work on it in future if schedule permits.

Sorry about inconvenience.


Thanks

Thanks,
Sathiya Shunmugasundaram
Digital Engineering – Platforms & Frameworks
804.381.9252 (cell)
Sathiya.Shunmugasundaram@Capitalone.com
[cid:D197CE4A-E731-48A9-91D6-46BD3CA51D16]

**Comment by dturanski** [comment]
Closing per author's comment.

**Pull request closed without merging**
