### PR TITLE
XD-2472: Kafka messagebus option: async vs sync producer

### PR DESCRIPTION
**Pull request by martindam**
Use the new updated Spring Integration kafka producer that supports synchronous producer

### CODE REVIEW

**Comment by martindam** [comment]
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

**Comment by mbogoevici** [comment]
Hi @martindam,

Thanks for the contribution. Of note, this also requires updating https://github.com/spring-projects/spring-xd/blob/master/spring-xd-messagebus-kafka/src/main/resources/META-INF/spring-xd/bus/kafka-bus.xml for passing in the defaults.

**Comment by martindam** [comment]
Hi @mbogoevici 

Thanks for the fast response. You are right, I fixed the issue.

**Comment by mbogoevici** [comment]
Rebased, squashed, merged w/https://github.com/spring-projects/spring-xd/commit/887f3adee90105492bcc11c4e793a0d4c65ca34a

**Comment by mbogoevici** [comment]
Sorry for the long delay in merging this. Thanks for the contribution!

**Pull request closed without merging**
