### PR TITLE
Fix license headers

### PR DESCRIPTION
**Pull request by dturanski**
backport https://github.com/spring-projects/spring-xd/commit/73c5237e7f0ef4f653113ed4cdbd14003cdd8cc0

### CODE REVIEW

**Comment by garyrussell** [comment]
@dturanski This needs to be rebased; rebasing to 1.0.x causes many conflicts.

**Comment by garyrussell** [comment]
After further review; it was indeed previously backported - is your 1.0.x branch up to data?

**Comment by dturanski** [comment]
I forgot to merge I guess. Sorry for the confusion

**Comment by garyrussell** [comment]
invalid

**Pull request closed without merging**
