### PR TITLE
[Sprint: 60] XD-3637: Bump SI, SF, AMQP Versions

### PR DESCRIPTION
**Pull request by garyrussell**
JIRA: https://jira.spring.io/browse/XD-3637

- Spring Integration 4.2.1
- Spring Framework 4.2.2
- Spring AMQP 1.5.1

__do not merge until SI 4.2.1 is in the repo__

### CODE REVIEW

**Comment by artembilan** [comment]
Spring Integration 4.2.1 is in the `/release` repo:
https://repo.spring.io/webapp/#/artifacts/browse/tree/General/release/org/springframework/integration/spring-integration-bom/4.2.1.RELEASE
, as well as in the `jcenter()` already:
https://bintray.com/spring/jars/org.springframework.integration/4.2.1.RELEASE/view#files
`mavenCentral()` sync takes several hours though...
Anyway:
http://search.maven.org/#search|ga|1|spring-integration-bom

**Comment by artembilan** [comment]
Quoting Bintray:
> The responsiveness of the Maven Central gateway at Sonatype fluctuates. This operation may take several minutes depending on the weather.

**Comment by garyrussell** [comment]
@artembilan it's only the search that lags behind; you can check whether the sync was successful at 

https://bintray.com/spring/jars/org.springframework.integration/4.2.1.RELEASE/view#central

`Last Sync Status: Successfully synced and closed repo.`

You don't have to wait for it to show up in maven search.

**Comment by markpollack** [comment]
merged 1fc03b4b8b24a3daa6c1e1290c2d6294e6f578fd

**Pull request closed without merging**
