### PR TITLE
[Sprint: 50] XD-3116: Update bundled redis to 3.0.1

### PR DESCRIPTION
**Pull request by ericbottard**
Tested redis build on mac osx 64bits

### CODE REVIEW

**Comment by ericbottard** [comment]
From the JIRA description: "RPM scripts will need to change.", not sure where those are

**Comment by markpollack** [comment]
@sabbyanandan how should we handle the rpms?

**Comment by markpollack** [comment]
The `install-redis` script needs to be updated as well, will do on merge.

**Comment by ericbottard** [comment]
I did update the script. Which bit are you referring to?

**Comment by markpollack** [comment]
there is a version number in `spring-xd/redis/bin/install-redis`.  May also be some other refs to some version in the README or docs....

**Comment by ericbottard** [comment]
`spring-xd/redis/bin/install-redis` is derived from the file I updated, unless I'm mistaken (the gradle build seemed awfully complicated to me, but I think I got it right).

**Comment by markpollack** [comment]
Verified on Ubuntu 14.04

**Comment by markpollack** [comment]
merged as 06863c3a54625ecd2c125369572f1ad6561efcb3

**Pull request closed without merging**
