### PR TITLE
[Sprint: 51] XD-3160: Reorganize modules alphabetically

### PR DESCRIPTION
**Pull request by ericbottard**
Man, that was fun...

Also removed the "Introduction" section title, so that it does not appear as module name in the TOC.

### CODE REVIEW

**Comment by dturanski** [comment]
For consistency, should we do the same for Jobs and Counters-and-Gauges?

**Comment by ericbottard** [comment]
Arf, missed jobs. Silly me.
Looked at counters & gauges and thought it was ok. I've never been too good
with alphabet though :)
Will update the PR

**Comment by ericbottard** [comment]
Updated jobs.
Leaving counters as is, as the narrative builds from simple to complex metrics and there are a lot of back references.

**Comment by dturanski** [comment]
merged;

**Pull request closed without merging**
