### PR TITLE
[Sprint 50]XD-3124 Propagate `minPartitionCount` to consumer properties

### PR DESCRIPTION
**Pull request by mbogoevici**
- ensure that the consumer end of the bus is in sync with the producer on the expected partition count
- update tests

### CODE REVIEW

**Comment by markpollack** [comment]
Will apply to 1.1.x, 1.2.0.RC, and master branches.

**Comment by markpollack** [comment]
Merged into 1.2.0.RC1 as 621ff48be365d2eca503e39028ccd406baab3453

**Comment by markpollack** [comment]
Merged into master as e53b591cc9eeb75597501c00e23223fc9c0f13fb

**Comment by mbogoevici** [comment]
Will make a separate PR for 1.1.x, to deal with conflicts.

**Pull request closed without merging**
