### PR TITLE
[Sprint: 44] XD-2741 - Redis sink default to spring.redis configuration in servers.yml

### PR DESCRIPTION
**Pull request by markpollack**

### CODE REVIEW

**Comment by garyrussell** [comment]
Shouldn't we do this the same way as it's done in the [RabbitConnectionMixin](https://github.com/spring-projects/spring-xd/blob/master/spring-xd-dirt/src/main/java/org/springframework/xd/dirt/modules/metadata/RabbitConnectionMixin.java#L33) ?

Also, this is misnamed; it's 2741 not 2471.

**Comment by markpollack** [comment]
I was following the pattern for jdbc I think.  There maybe some overall inconsistency.  I'll look into it more.

**Comment by garyrussell** [comment]
Yes, I see - I have opened https://jira.spring.io/browse/XD-2768 to resolve the inconsistencies and will merge this as-is.

**Comment by garyrussell** [comment]
Merged and cherry-picked to 1.1.x.

**Pull request closed without merging**
