### PR TITLE
[Sprint: 45] XD-2774 Fix error handling in jdbchdfs job

### PR DESCRIPTION
**Pull request by trisberg**

### CODE REVIEW

**Comment by mminella** [comment]
Why doesn't this writer take the same approach as the {{FlatFileItemWriter}} with a transaction aware buffer of some kind ({{TransactionAwareBufferedWriter}} in it's case)?

**Comment by trisberg** [comment]
Don't know, that's a different issue though, maybe create a new story for that. We are also considering re-writing this job to have a more direct path from jdbc->hdfs and not use the chunk approach to speed things up.

**Comment by mminella** [comment]
I ask because of the lifecycle of a transaction.  However, if we're going to gut this for a more high speed approach, then nevermind.  Merged.

**Comment by trisberg** [comment]
We need this backported to 1.1.x branch as well

**Comment by mminella** [comment]
Coming right up

**Comment by mminella** [comment]
Ported to 1.1.x

**Pull request closed without merging**
