### PR TITLE
[Sprint: 50] XD-2899: Add Missing Props to servers.yml

### PR DESCRIPTION
**Pull request by garyrussell**

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
I think we need these property in `spring-xd-yarn`'s servers.yml as well.

**Comment by ilayaperumalg** [comment]
I can add while merging.

**Comment by ilayaperumalg** [comment]
LGTM, merged along with the change to include the properties into YARN config servers.yml: 7474f0c14cf573be859b856344e694f5d933921a

**Comment by garyrussell** [comment]
Yikes! I didn't know we had YAYF (yet another yaml file) :frowning:

**Comment by markpollack** [comment]
cherry picked into 1.2.0.RC1 as 7474f0c14cf573be859b856344e694f5d933921a

**Pull request closed without merging**
