### PR TITLE
[Sprint: 50] XD-3148 Adding exclusion to remove hadoop-core-2.5.0-mr1-cdh5.3.3.jar…

### PR DESCRIPTION
**Pull request by trisberg**
… from dist

### CODE REVIEW

**Comment by jvalkeal** [comment]
Oh dear Thomas, how on earth I'm supposed to test this?

**Comment by trisberg** [comment]
Just build the distribution files and compare the xd/lib/cdh5 directory content with what is in 1.2.0.RC1

**Comment by jvalkeal** [comment]
looks ok, merging, just adding comment here for jetty-util

This patch changes that
```
$ diff /tmp/cdh.1 /tmp/cdh.2
8d7
< hadoop-core-2.5.0-mr1-cdh5.3.3.jar
28c27
< jetty-util-6.1.26.jar
---
> jetty-util-6.1.26.cloudera.4.jar
```
We seem to have jetty-util also directly under lib.
```
$ find . |grep jetty-util
./phd21/jetty-util-6.1.26.jar
./phd21/jetty-util-7.6.10.v20130312.jar
./jetty-util-6.1.26.jar
./hdp22/jetty-util-6.1.26.jar
./jetty-util-8.1.14.v20131031.jar
./hadoop26/jetty-util-6.1.26.jar
./cdh5/jetty-util-6.1.26.cloudera.4.jar
./phd30/jetty-util-6.1.26.jar
```

**Comment by jvalkeal** [comment]
merged

**Pull request closed without merging**
