### PR TITLE
[Sprint 47] XD-2984 Move hadoopDistro option to CommonOptions

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Since both the `admin` and `container` use `--hadoopDistro` option
we can have this option moved to `CommonOptions`
 - Fix XD config logger to log `hadooDistro` option for all the runtime JVMs.

### CODE REVIEW

**Comment by trisberg** [comment]
Shouldn't the handling of the --hadoopDistro option in the xd-admin and xd-container be the same? I would think that what is in xd-container is the best code to also use on xd-admin script rather than enumerate the hadoop versions supported in the script as well. This is already handled by the HadoopDistroOptionHandler.

**Comment by ilayaperumalg** [comment]
@trisberg I see your point. I will modify the xd-admin script and update the PR.

**Comment by ilayaperumalg** [comment]
@trisberg Updated the PR after fixing the admin scripts to use the OptionsHandler to validate the hadoop distro option.

**Comment by trisberg** [comment]
LGTM, merging ...

**Pull request closed without merging**
