### PR TITLE
[Sprint: 49] [master + backport] XD-2924 Tap spark processor output

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add support to tap spark streaming processor module's output
   - Add wiretap channel to processor module output channel
   - Bind wiretap channel to messagebus pub/sub producer
   - Unbind/close wiretap channel upon module stop

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Please note I haven't added the logic to use TapListeners to update ZK path in case of taps created on spark streaming processor's output channel. Since the `MessageBusSender` (where the output channel is bound to the messagebus) is running on spark cluster, building/binding the tap is done at the MessageBusSender itself.

**Comment by markfisher** [comment]
I understand not wanting to connect to ZK from the module running on the Spark cluster just for the functionality where we enable publishing to a tap channel only when at least 1 subscriber is active. However, it's not very likely that a tap will be used at that location, definitely not the "normal" case. I wonder if we should instead support a boolean option for Spark Streaming modules that would explicitly enable the publishing to a tap channel. It would be FALSE by default, but if someone deploying the module knows they are going to create taps off that pipe, the could set that option value to TRUE.

**Comment by ilayaperumalg** [comment]
@markfisher yeah, that's a good idea. I will work on adding an explicit option to create tap.

**Comment by ilayaperumalg** [comment]
@markfisher Added support to enable tap on the spark processor output via a module option named `enableTap`. Please note that since this support uses module option, one can specify it for the sink module as well (with no consequences). I have created a JIRA to differentiate the module option classes for spark processor/sink modules: https://jira.spring.io/browse/XD-3002

**Comment by markfisher** [comment]
LGTM

**Comment by ilayaperumalg** [comment]
Squashed and merged as 32bda437ffdccdd0828804583377acd82c4a7f53. Also, back-ported to 1.1.x as 39539aeaac3bdbd12a5eb38710c6dfb6569543ff

**Pull request closed without merging**
