### PR TITLE
[Sprint: 47] XD-2775 Updating spring-data-hadoop to version 2.1.2.RELEASE

### PR DESCRIPTION
**Pull request by trisberg**

### CODE REVIEW

**Comment by cppwfs** [comment]
LGTM.

**Comment by trisberg** [comment]
It's in Sprint 47 - https://jira.spring.io/browse/XD-2775

**Comment by cppwfs** [comment]
Thanks Thomas.  I missed that it was a subtask.

--Glenn

**Comment by cppwfs** [comment]
Rebase Merged

**Pull request closed without merging**
